import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export default async function ProjectDocuments({params}:{params:{projectId:string}}){
 const s=createClient(); const {data:documents,error}=await s.from("documents").select("id,title,category,reference,document_date,notes,attachment_id,uploaded_at").eq("project_id",params.projectId).order("uploaded_at",{ascending:false});
 const ids=(documents??[]).map((d:any)=>d.attachment_id).filter(Boolean); const {data:attachments}=ids.length?await s.from("attachments").select("id,file_name,storage_path,mime_type").in("id",ids):{data:[] as any[]}; const byId=new Map((attachments??[]).map((a:any)=>[a.id,a]));
 const rows=await Promise.all((documents??[]).map(async(d:any)=>{const a:any=byId.get(d.attachment_id);if(!a?.storage_path)return{...d,attachment:a,url:null};const {data}=await s.storage.from("project-documents").createSignedUrl(a.storage_path,3600);return{...d,attachment:a,url:data?.signedUrl??null}}));
 return <div className="min-w-0 space-y-5"><div><h1 className="text-xl font-semibold">Project Documents</h1><p className="text-sm text-gray-500">Contracts, approvals, drawings, certificates and site records for this project.</p></div>
 <section className="rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Document register</div>{error&&<p className="p-4 text-sm text-red-600">{error.message}</p>}<div className="space-y-3 p-3 md:hidden">{rows.map((d:any)=><Card key={d.id} d={d}/>)}{!error&&!rows.length&&<p className="p-3 text-sm text-gray-500">No documents uploaded for this project.</p>}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr><th className="px-4 py-2">Date</th><th>Category</th><th>Title</th><th>Reference</th><th>File</th><th className="pr-4">Action</th></tr></thead><tbody>{rows.map((d:any)=><tr key={d.id} className="border-t"><td className="px-4 py-3">{d.document_date??"—"}</td><td>{d.category??"—"}</td><td className="font-medium">{d.title}</td><td>{d.reference??"—"}</td><td>{d.attachment?.file_name??"—"}</td><td className="pr-4">{d.url?<a href={d.url} target="_blank" rel="noreferrer" className="text-active hover:underline">View</a>:"—"}</td></tr>)}{!error&&!rows.length&&<tr><td colSpan={6} className="p-6 text-center text-gray-500">No documents uploaded for this project.</td></tr>}</tbody></table></div></section></div>
}
function Card({d}:{d:any}){return <div className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-medium">{d.title}</div><div className="text-xs text-gray-500">{d.document_date??"No document date"}{d.reference?" · "+d.reference:""}</div></div><span className="shrink-0 rounded-full bg-gray-100 px-2 py-1 text-[11px]">{d.category??"Other"}</span></div>{d.notes&&<div className="mt-2 text-xs text-gray-500">{d.notes}</div>}{d.url&&<a href={d.url} target="_blank" rel="noreferrer" className="mt-3 inline-block rounded border border-border px-3 py-1.5 text-xs font-medium text-active">View document</a>}</div>}
