import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { fmtDate, pkr } from "@/lib/format";
const value=(f:FormData,k:string)=>String(f.get(k)??"").trim();
async function issueMaterial(formData:FormData){"use server";const supabase=createClient();const project=value(formData,"project_id"),material=value(formData,"material_id"),boq=value(formData,"boq_item_id");const quantity=Number(formData.get("quantity")??0);if(!project||!material||!Number.isFinite(quantity)||quantity<=0)throw new Error("Project, material and a positive quantity are required.");const {error}=await supabase.rpc("issue_material",{p_project:project,p_material:material,p_quantity:quantity,p_boq_item:boq||null,p_issued_to:value(formData,"issued_to")||null,p_date:value(formData,"issue_date"),p_remarks:value(formData,"remarks")||null});if(error)throw new Error(error.message);revalidatePath("/materials");revalidatePath("/dashboard");}
export const dynamic="force-dynamic";
export default async function MaterialsPage(){const supabase=createClient();const [{data:projects},{data:materials},{data:balances,error},{data:transactions},{data:boqItems}]=await Promise.all([
supabase.from("projects").select("id,project_code,project_name").eq("status","active").order("project_code"),
supabase.from("materials").select("id,material_code,name,units:base_unit_id(code)").order("name"),
supabase.from("v_stock_balance").select("project_id,material_id,material_name,balance_quantity,average_cost,stock_value,received_quantity,issued_quantity,stock_location_id"),
supabase.from("stock_transactions").select("id,project_id,material_id,txn_type,quantity,unit_cost,amount,txn_date,boq_item_id,materials(name,material_code,units:base_unit_id(code)),projects(project_code,project_name),boq_items(boq_number,description)").order("txn_date",{ascending:false}).order("created_at",{ascending:false}).limit(100),
supabase.from("boq_items").select("id,project_id,boq_number,description").order("sort_order").limit(1000)]);
const projectMap=new Map((projects??[]).map((p:any)=>[p.id,p]));
return <div className="space-y-5"><div><h1 className="text-xl font-semibold">Materials & Project Stock</h1><p className="text-sm text-muted-foreground">Purchased material enters project stock. Material issues record actual site consumption separately.</p></div>
<section className="rounded-xl border border-border bg-white p-4"><h2 className="font-semibold">Issue material to site</h2><p className="mb-4 text-sm text-muted-foreground">Use this when material leaves the project store for work. BOQ allocation is optional but recommended.</p><form action={issueMaterial} className="grid gap-3 md:grid-cols-4">
<select name="project_id" required className="rounded-md border px-3 py-2 text-sm"><option value="">Select project</option>{(projects??[]).map((p:any)=><option key={p.id} value={p.id}>{p.project_code} — {p.project_name}</option>)}</select>
<select name="material_id" required className="rounded-md border px-3 py-2 text-sm"><option value="">Select material</option>{(materials??[]).map((m:any)=><option key={m.id} value={m.id}>{m.name} ({m.units?.code??""})</option>)}</select>
<input name="quantity" type="number" min="0.001" step="any" required placeholder="Quantity issued" className="rounded-md border px-3 py-2 text-sm"/><input name="issue_date" type="date" required className="rounded-md border px-3 py-2 text-sm"/>
<select name="boq_item_id" className="rounded-md border px-3 py-2 text-sm"><option value="">BOQ item (optional)</option>{(boqItems??[]).map((b:any)=><option key={b.id} value={b.id}>{b.boq_number} — {b.description}</option>)}</select><input name="issued_to" placeholder="Issued to / person / team" className="rounded-md border px-3 py-2 text-sm"/><input name="remarks" placeholder="Remarks / work location" className="rounded-md border px-3 py-2 text-sm md:col-span-2"/><button className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 md:col-span-4">Issue material</button></form></section>
<section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Project stock balance</div>{error?<p className="p-4 text-sm text-red-600">{error.message}</p>:(balances??[]).length===0?<p className="p-6 text-center text-sm text-muted-foreground">No project stock yet. Posted purchases will appear here.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs text-muted-foreground"><th className="px-4 py-2">Project</th><th>Material</th><th className="text-right">Received</th><th className="text-right">Issued / Consumed</th><th className="text-right">Balance</th><th className="text-right">Avg Cost</th><th className="px-4 text-right">Stock Value</th></tr></thead><tbody>{(balances??[]).map((r:any)=>{const p:any=projectMap.get(r.project_id);const m:any=(materials??[]).find((x:any)=>x.id===r.material_id);return <tr key={r.project_id+"-"+r.material_id+"-"+r.stock_location_id} className="border-b last:border-0"><td className="px-4 py-3"><span title={p?.project_name??""}>{p?.project_code??"Project"}</span></td><td><span className="font-medium" title={m?.material_code?("Material code: "+m.material_code):""}>{r.material_name}</span><span className="ml-1 text-xs text-muted-foreground">{m?.units?.code??""}</span></td><td className="text-right">{Number(r.received_quantity??0).toLocaleString("en-PK")}</td><td className="text-right">{Number(r.issued_quantity??0).toLocaleString("en-PK")}</td><td className="text-right font-semibold">{Number(r.balance_quantity??0).toLocaleString("en-PK")}</td><td className="text-right">{pkr(Number(r.average_cost??0))}</td><td className="px-4 text-right font-medium">{pkr(Number(r.stock_value??0))}</td></tr>})}</tbody></table></div>}</section>
<section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Stock transaction history</div>{(transactions??[]).length===0?<p className="p-6 text-center text-sm text-muted-foreground">No stock transactions yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs text-muted-foreground"><th className="px-4 py-2">Date</th><th>Project</th><th>Material</th><th>Type</th><th className="text-right">Qty</th><th>BOQ / Work</th><th className="px-4 text-right">Value</th></tr></thead><tbody>{(transactions??[]).map((t:any)=><tr key={t.id} className="border-b last:border-0"><td className="px-4 py-3">{fmtDate(t.txn_date)}</td><td>{t.projects?.project_code??"—"}</td><td><span title={t.materials?.material_code?("Material code: "+t.materials.material_code):""}>{t.materials?.name??"Material"}</span></td><td className="uppercase">{String(t.txn_type??"").replaceAll("_"," ")}</td><td className="text-right">{Number(t.quantity??0).toLocaleString("en-PK")} {t.materials?.units?.code??""}</td><td className="max-w-[280px] truncate" title={t.boq_items?.description??""}>{t.boq_items?(t.boq_items.boq_number+" — "+t.boq_items.description):"—"}</td><td className="px-4 text-right">{pkr(Math.abs(Number(t.amount??0)))}</td></tr>)}</tbody></table></div>}</section></div>}