import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { fmtDate, pkr } from "@/lib/format";
import MaterialIssueForm from "@/components/materials/MaterialIssueForm";
const value=(f:FormData,k:string)=>String(f.get(k)??"").trim();
async function issueMaterial(formData:FormData){"use server";let message="";try{const supabase=createClient();const project=value(formData,"project_id"),material=value(formData,"material_id"),boq=value(formData,"boq_item_id");const quantity=Number(formData.get("quantity")??0);if(!project||!material||!Number.isFinite(quantity)||quantity<=0)throw new Error("Project, material and a positive quantity are required.");if(boq){const {data:boqRow,error:boqError}=await supabase.from("boq_items").select("project_id").eq("id",boq).single();if(boqError||boqRow?.project_id!==project)throw new Error("Selected BOQ item does not belong to the selected project.");}const {error}=await supabase.rpc("issue_material",{p_project:project,p_material:material,p_quantity:quantity,p_boq_item:boq||null,p_issued_to:value(formData,"issued_to")||null,p_date:value(formData,"issue_date")||null,p_remarks:value(formData,"remarks")||null});if(error)throw new Error(error.message);revalidatePath("/materials");revalidatePath("/dashboard");}catch(e){message=e instanceof Error?e.message:"Unable to issue material.";}if(message)redirect("/materials?issueError="+encodeURIComponent(message));redirect("/materials?issued=1");}
export const dynamic="force-dynamic";
export default async function MaterialsPage({searchParams}:{searchParams?:{issueError?:string;issued?:string}}){const supabase=createClient();const [{data:projects},{data:materials},{data:balances,error},{data:transactions},{data:boqItems}]=await Promise.all([
supabase.from("projects").select("id,project_code,project_name").eq("status","active").order("project_code"),
supabase.from("materials").select("id,material_code,name,units:base_unit_id(code)").order("name"),
supabase.from("v_stock_balance").select("project_id,material_id,material_name,balance_quantity,average_cost,stock_value,received_quantity,issued_quantity,stock_location_id"),
supabase.from("stock_transactions").select("id,project_id,material_id,txn_type,quantity,unit_cost,amount,txn_date,boq_item_id,materials(name,material_code,units:base_unit_id(code)),projects(project_code,project_name),boq_items(boq_number,description)").order("txn_date",{ascending:false}).order("created_at",{ascending:false}).limit(100),
supabase.from("boq_items").select("id,project_id,boq_number,description").order("sort_order").limit(1000)]);
const projectMap=new Map((projects??[]).map((p:any)=>[p.id,p]));
return <div className="min-w-0 space-y-5"><div><h1 className="text-xl font-semibold">Materials & Project Stock</h1><p className="text-sm text-muted-foreground">Purchased material enters project stock. Material issues record actual site consumption separately.</p></div>
<section className="min-w-0 rounded-xl border border-border bg-white p-4"><h2 className="font-semibold">Issue material to site</h2>{searchParams?.issueError?<div className="my-3 rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{searchParams.issueError}</div>:searchParams?.issued?<div className="my-3 rounded-md bg-green-50 px-3 py-2 text-sm text-green-700">Material issued successfully and stock balance updated.</div>:null}<p className="mb-4 text-sm text-muted-foreground">Use this when material leaves the project store for work. BOQ allocation is optional but recommended.</p><MaterialIssueForm action={issueMaterial} projects={(projects??[]) as any} materials={(materials??[]).map((m:any)=>({id:m.id,name:m.name,material_code:m.material_code,unit:m.units?.code??""}))} balances={(balances??[]).map((b:any)=>({project_id:b.project_id,material_id:b.material_id,balance_quantity:Number(b.balance_quantity??0)}))} boqItems={(boqItems??[]) as any}/></section>
<section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Project stock balance</div>{error?<p className="p-4 text-sm text-red-600">{error.message}</p>:(balances??[]).length===0?<p className="p-6 text-center text-sm text-muted-foreground">No project stock yet. Posted purchases will appear here.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs text-muted-foreground"><th className="px-4 py-2">Project</th><th>Material</th><th className="text-right">Received</th><th className="text-right">Issued / Consumed</th><th className="text-right">Balance</th><th className="text-right">Avg Cost</th><th className="px-4 text-right">Stock Value</th></tr></thead><tbody>{(balances??[]).map((r:any)=>{const p:any=projectMap.get(r.project_id);const m:any=(materials??[]).find((x:any)=>x.id===r.material_id);return <tr key={r.project_id+"-"+r.material_id+"-"+r.stock_location_id} className="border-b last:border-0"><td className="px-4 py-3"><span title={p?.project_name??""}>{p?.project_code??"Project"}</span></td><td><span className="font-medium" title={m?.material_code?("Material code: "+m.material_code):""}>{r.material_name}</span><span className="ml-1 text-xs text-muted-foreground">{m?.units?.code??""}</span></td><td className="text-right">{Number(r.received_quantity??0).toLocaleString("en-PK")}</td><td className="text-right">{Number(r.issued_quantity??0).toLocaleString("en-PK")}</td><td className="text-right font-semibold">{Number(r.balance_quantity??0).toLocaleString("en-PK")}</td><td className="text-right">{pkr(Number(r.average_cost??0))}</td><td className="px-4 text-right font-medium">{pkr(Number(r.stock_value??0))}</td></tr>})}</tbody></table></div>}</section>
<section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Stock transaction history</div>{(transactions??[]).length===0?<p className="p-6 text-center text-sm text-muted-foreground">No stock transactions yet.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b bg-gray-50 text-left text-xs text-muted-foreground"><th className="px-4 py-2">Date</th><th>Project</th><th>Material</th><th>Type</th><th className="text-right">Qty</th><th>BOQ / Work</th><th className="px-4 text-right">Value</th></tr></thead><tbody>{(transactions??[]).map((t:any)=><tr key={t.id} className="border-b last:border-0"><td className="px-4 py-3">{fmtDate(t.txn_date)}</td><td>{t.projects?.project_code??"—"}</td><td><span title={t.materials?.material_code?("Material code: "+t.materials.material_code):""}>{t.materials?.name??"Material"}</span></td><td className="uppercase">{String(t.txn_type??"").replaceAll("_"," ")}</td><td className="text-right">{Number(t.quantity??0).toLocaleString("en-PK")} {t.materials?.units?.code??""}</td><td className="max-w-[280px] truncate" title={t.boq_items?.description??""}>{t.boq_items?(t.boq_items.boq_number+" — "+t.boq_items.description):"—"}</td><td className="px-4 text-right">{pkr(Math.abs(Number(t.amount??0)))}</td></tr>)}</tbody></table></div>}</section></div>}