"use client";
import {useMemo,useRef,useState} from "react";
type P={id:string;project_code:string;project_name:string};
type E={id:string;name:string;ownership:string};
type B={id:string;project_id:string;boq_number:string;description:string};
export default function MachineryLogForm({action,projects,equipment,boqItems}:{action:(fd:FormData)=>void;projects:P[];equipment:E[];boqItems:B[]}){
 const ref=useRef<HTMLFormElement>(null);
 const[pid,setPid]=useState(""),[bid,setBid]=useState(""),[q,setQ]=useState(""),[open,setOpen]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
 const items=useMemo(()=>{const s=q.trim().toLowerCase();return boqItems.filter(x=>x.project_id===pid&&(!s||(`${x.boq_number} ${x.description}`).toLowerCase().includes(s))).slice(0,50)},[boqItems,pid,q]);
 async function submit(fd:FormData){setPending(true);setError(null);setSuccess(null);try{await action(fd);ref.current?.reset();setPid("");setBid("");setQ("");setOpen(false);setSuccess("Machinery log saved successfully.");}catch(e:any){setError(e?.message??"Could not save machinery log.");}finally{setPending(false)}}
 return <form ref={ref} action={submit} className="space-y-3 rounded-xl border bg-white p-5 lg:col-span-2"><h2 className="font-semibold">Daily machinery log</h2>{error&&<div className="rounded bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}{success&&<div className="rounded bg-green-50 px-3 py-2 text-sm text-green-700">{success}</div>}<div className="grid gap-3 md:grid-cols-3"><select name="project_id" required value={pid} onChange={e=>{setPid(e.target.value);setBid("");setQ("");setOpen(false)}} className="min-w-0 w-full rounded-md border px-3 py-2"><option value="">Select project</option>{projects.map(x=><option key={x.id} value={x.id}>{x.project_code} — {x.project_name}</option>)}</select><select name="equipment_id" required className="min-w-0 w-full rounded-md border px-3 py-2"><option value="">Select equipment</option>{equipment.map(x=><option key={x.id} value={x.id}>{x.name} ({x.ownership})</option>)}</select><input name="log_date" type="date" required className="min-w-0 w-full rounded-md border px-3 py-2"/><input name="operating_hours" type="number" min="0" step=".01" placeholder="Operating hours" className="min-w-0 w-full rounded-md border px-3 py-2"/><input name="idle_hours" type="number" min="0" step=".01" placeholder="Idle hours" className="min-w-0 w-full rounded-md border px-3 py-2"/><input name="fuel_consumption" type="number" min="0" step=".01" placeholder="Fuel consumed" className="min-w-0 w-full rounded-md border px-3 py-2"/><input name="rental_cost" type="number" min="0" step=".01" placeholder="Rental cost (Rs)" className="min-w-0 w-full rounded-md border px-3 py-2"/><input name="maintenance_cost" type="number" min="0" step=".01" placeholder="Maintenance cost (Rs)" className="min-w-0 w-full rounded-md border px-3 py-2"/><div className="relative min-w-0"><input type="hidden" name="boq_item_id" value={bid}/><input value={q} disabled={!pid} onFocus={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{setQ(e.target.value);setBid("");setOpen(true)}} placeholder={pid?"Search BOQ no. or description":"Select project first"} className="min-w-0 w-full rounded-md border px-3 py-2 disabled:bg-gray-50"/>{open&&pid&&<div className="absolute z-30 mt-1 max-h-64 w-full overflow-y-auto rounded-md border bg-white shadow-lg">{items.length?items.map(x=><button key={x.id} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setBid(x.id);setQ(`${x.boq_number} — ${x.description}`);setOpen(false)}} className="block w-full border-b px-3 py-2 text-left text-sm last:border-0 hover:bg-gray-50"><b>{x.boq_number}</b> — {x.description}</button>):<div className="p-3 text-sm text-gray-500">No matching BOQ items.</div>}</div>}</div></div><button disabled={pending} className="w-full rounded-md bg-blue-600 px-4 py-2 text-white disabled:opacity-60">{pending?"Saving...":"Save machinery log"}</button></form>
}