import { createClient } from "@/lib/supabase/server";
import { pkr } from "@/lib/format";
export const dynamic="force-dynamic";
export default async function ProjectCosts({params}:{params:{projectId:string}}){
 const s=createClient(); const {data:expenses,error}=await s.from("expenses").select("id,expense_number,expense_date,classification,payee,description,amount,payment_method,status,expense_categories(name),boq_items(boq_number,description)").eq("project_id",params.projectId).order("expense_date",{ascending:false}).limit(100);
 const total=(expenses??[]).reduce((n:any,e:any)=>n+Number(e.amount??0),0),direct=(expenses??[]).filter((e:any)=>e.classification==="direct_boq").reduce((n:any,e:any)=>n+Number(e.amount??0),0),overhead=total-direct;
 return <div className="min-w-0 space-y-5"><div><h1 className="text-xl font-semibold">Project Costs</h1><p className="text-sm text-gray-500">Direct BOQ costs and project overhead remain separately classified.</p></div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Metric label="Total expenses" value={pkr(total)}/><Metric label="Direct BOQ cost" value={pkr(direct)}/><Metric label="Project overhead" value={pkr(overhead)}/></div>
 <section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Project expense register</div>{error?<p className="p-4 text-sm text-red-600">{error.message}</p>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="px-4 py-2 text-left">Date</th><th className="text-left">Category</th><th className="text-left">Classification</th><th className="text-left">Payee / Description</th><th className="text-left">Status</th><th className="px-4 text-right">Amount</th></tr></thead><tbody>{(expenses??[]).map((e:any)=><tr key={e.id} className="border-t"><td className="px-4 py-3">{e.expense_date}</td><td>{e.expense_categories?.name??"—"}</td><td>{e.classification==="direct_boq"?"Direct BOQ":"Overhead"}</td><td>{e.payee??"—"}<div className="max-w-[320px] truncate text-xs text-gray-500">{e.description??""}</div></td><td className="uppercase">{e.status}</td><td className="px-4 text-right font-medium">{pkr(Number(e.amount??0))}</td></tr>)}{!(expenses??[]).length&&<tr><td colSpan={6} className="p-6 text-center text-gray-500">No expenses recorded for this project.</td></tr>}</tbody></table></div>}</section></div>
}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-xl border border-border bg-white p-4"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>}
