import { createClient } from "@/lib/supabase/server";
import { fmtDate, pkr } from "@/lib/format";
export const dynamic="force-dynamic";
export default async function ProjectMaterials({params}:{params:{projectId:string}}){
 const s=createClient(); const [{data:balances,error},{data:transactions}]=await Promise.all([
  s.from("v_stock_balance").select("project_id,material_id,material_name,balance_quantity,average_cost,stock_value,received_quantity,issued_quantity,stock_location_id").eq("project_id",params.projectId),
  s.from("stock_transactions").select("id,txn_type,quantity,amount,txn_date,materials(name,material_code,units:base_unit_id(code)),boq_items(boq_number,description)").eq("project_id",params.projectId).order("txn_date",{ascending:false}).limit(50)
 ]);
 const stockValue=(balances??[]).reduce((n:any,r:any)=>n+Number(r.stock_value??0),0);
 return <div className="min-w-0 space-y-5"><div><h1 className="text-xl font-semibold">Project Materials</h1><p className="text-sm text-gray-500">Stock balances and material movement for this project.</p></div>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Metric label="Materials in stock" value={String((balances??[]).filter((r:any)=>Number(r.balance_quantity)>0).length)}/><Metric label="Stock value" value={pkr(stockValue)}/><Metric label="Recent transactions" value={String((transactions??[]).length)}/></div>
 <section className="overflow-hidden rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Stock balance</div>{error?<p className="p-4 text-sm text-red-600">{error.message}</p>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr><th className="px-4 py-2 text-left">Material</th><th className="text-right">Received</th><th className="text-right">Issued</th><th className="text-right">Balance</th><th className="px-4 text-right">Value</th></tr></thead><tbody>{(balances??[]).map((r:any)=><tr key={r.material_id+"-"+r.stock_location_id} className="border-t"><td className="px-4 py-3 font-medium">{r.material_name}</td><td className="text-right">{Number(r.received_quantity??0).toLocaleString("en-PK")}</td><td className="text-right">{Number(r.issued_quantity??0).toLocaleString("en-PK")}</td><td className="text-right font-semibold">{Number(r.balance_quantity??0).toLocaleString("en-PK")}</td><td className="px-4 text-right">{pkr(Number(r.stock_value??0))}</td></tr>)}{!(balances??[]).length&&<tr><td colSpan={5} className="p-6 text-center text-gray-500">No project stock yet.</td></tr>}</tbody></table></div>}</section>
 <section className="rounded-xl border border-border bg-white"><div className="border-b px-4 py-3 font-semibold">Recent material activity</div><div className="divide-y">{(transactions??[]).map((t:any)=><div key={t.id} className="grid grid-cols-[1fr_auto] gap-3 px-4 py-3 text-sm"><div><div className="font-medium">{t.materials?.name??"Material"} · {String(t.txn_type??"").replaceAll("_"," ")}</div><div className="text-xs text-gray-500">{fmtDate(t.txn_date)}{t.boq_items?" · "+t.boq_items.boq_number:""}</div></div><div className="text-right"><div>{Number(t.quantity??0).toLocaleString("en-PK")} {t.materials?.units?.code??""}</div><div className="text-xs text-gray-500">{pkr(Math.abs(Number(t.amount??0)))}</div></div></div>)}{!(transactions??[]).length&&<p className="p-4 text-sm text-gray-500">No material transactions yet.</p>}</div></section></div>
}
function Metric({label,value}:{label:string,value:string}){return <div className="rounded-xl border border-border bg-white p-4"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>}
