export const dynamic="force-dynamic";
import {createClient} from "@/lib/supabase/server";import {revalidatePath} from "next/cache";import {CreateBillForm,BillItemForm} from "@/components/bills/RABillForms";import {SubmitBill,CertificationForm,BillStatusAction} from "@/components/bills/RABillWorkflow";import {pkr} from "@/lib/format";
const tv=(f:FormData,n:string)=>{const v=String(f.get(n)??"").trim();return v||null};const nv=(f:FormData,n:string)=>{const r=String(f.get(n)??"").trim(),v=Number(r);return r&&Number.isFinite(v)?v:null};
async function createBill(f:FormData){"use server";const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user)throw new Error("Sign in required.");const projectId=tv(f,"project_id"),bill=tv(f,"bill_number"),from=tv(f,"period_from"),to=tv(f,"period_to");if(!projectId||!bill||!from||!to)throw new Error("Bill number and period are required.");if(from>to)throw new Error("Period from cannot be after period to.");const {error}=await s.from("ra_bills").insert({project_id:projectId,bill_number:bill,period_from:from,period_to:to,status:"draft",gross_claimed_amount:0,created_by:user.id});if(error)throw new Error("Could not create RA bill: "+error.message);revalidatePath("/projects/"+projectId+"/bills")}
async function addBillItem(f:FormData){"use server";const s=createClient();const projectId=tv(f,"project_id"),billId=tv(f,"ra_bill_id"),itemId=tv(f,"boq_item_id"),qty=nv(f,"claimed_quantity");if(!projectId||!billId||!itemId||qty===null||qty<=0)throw new Error("BOQ item and positive claimed quantity are required.");
const {data:bill}=await s.from("ra_bills").select("id,status").eq("id",billId).eq("project_id",projectId).maybeSingle();if(!bill||bill.status!=="draft")throw new Error("Claims can only be added to a draft RA bill.");
const {data:item}=await s.from("boq_items").select("id,original_quantity,contract_rate,rate_basis").eq("id",itemId).eq("project_id",projectId).maybeSingle();if(!item)throw new Error("BOQ item not found.");
const [{data:measurements},{data:previous},{data:vars}]=await Promise.all([s.from("measurements").select("measured_quantity").eq("boq_item_id",itemId),s.from("ra_bill_items").select("current_claimed_quantity,ra_bills!inner(project_id)").eq("boq_item_id",itemId).eq("ra_bills.project_id",projectId),s.from("boq_variations").select("approved_quantity").eq("boq_item_id",itemId).eq("status","approved")]);
const measured=(measurements??[]).reduce((a,m)=>a+Number(m.measured_quantity??0),0),prev=(previous??[]).reduce((a,i)=>a+Number(i.current_claimed_quantity??0),0),contractQty=Number(item.original_quantity)+(vars??[]).reduce((a,v)=>a+Number(v.approved_quantity??0),0);if(prev+qty>measured+0.000001)throw new Error("Claim exceeds measured quantity. Available to claim: "+Math.max(0,measured-prev).toLocaleString());
const rate=Number(item.contract_rate),amount=qty*rate/Number(item.rate_basis||1);const {error}=await s.from("ra_bill_items").insert({ra_bill_id:billId,boq_item_id:itemId,contract_quantity:contractQty,previous_billed_quantity:prev,current_claimed_quantity:qty,cumulative_claimed_quantity:prev+qty,rate,claimed_amount:amount});if(error)throw new Error("Could not add claim item: "+error.message);
const {data:rows}=await s.from("ra_bill_items").select("claimed_amount").eq("ra_bill_id",billId);await s.from("ra_bills").update({gross_claimed_amount:(rows??[]).reduce((a,r)=>a+Number(r.claimed_amount??0),0)}).eq("id",billId);revalidatePath("/projects/"+projectId+"/bills")}

async function submitBill(f:FormData){"use server";const s=createClient();const projectId=tv(f,"project_id"),billId=tv(f,"ra_bill_id"),date=tv(f,"submission_date");if(!projectId||!billId||!date)throw new Error("Submission date is required.");const {data:bill}=await s.from("ra_bills").select("id,status").eq("id",billId).eq("project_id",projectId).maybeSingle();if(!bill||bill.status!=="draft")throw new Error("Only draft bills can be submitted.");const {count}=await s.from("ra_bill_items").select("id",{count:"exact",head:true}).eq("ra_bill_id",billId);if(!count)throw new Error("Add at least one claim item before submission.");const {error}=await s.from("ra_bills").update({status:"submitted",submission_date:date}).eq("id",billId);if(error)throw new Error(error.message);revalidatePath("/projects/"+projectId+"/bills")}
async function certifyItem(f:FormData){"use server";const s=createClient();const projectId=tv(f,"project_id"),billId=tv(f,"ra_bill_id"),rowId=tv(f,"ra_bill_item_id"),qty=nv(f,"certified_quantity");if(!projectId||!billId||!rowId||qty===null||qty<0)throw new Error("A valid certified quantity is required.");const {data:bill}=await s.from("ra_bills").select("id,status").eq("id",billId).eq("project_id",projectId).maybeSingle();if(!bill||!["submitted","under_checking","verified"].includes(bill.status))throw new Error("Bill is not open for certification.");const {data:row}=await s.from("ra_bill_items").select("id,current_claimed_quantity,rate,boq_items(rate_basis)").eq("id",rowId).eq("ra_bill_id",billId).maybeSingle();if(!row)throw new Error("Claim item not found.");if(qty>Number(row.current_claimed_quantity)+0.000001)throw new Error("Certified quantity cannot exceed current claimed quantity.");const b:any=row.boq_items,basis=Number((Array.isArray(b)?b[0]?.rate_basis:b?.rate_basis)||1),amount=qty*Number(row.rate)/basis;const {error}=await s.from("ra_bill_items").update({certified_quantity:qty,certified_amount:amount}).eq("id",rowId);if(error)throw new Error(error.message);const {data:rows}=await s.from("ra_bill_items").select("certified_amount").eq("ra_bill_id",billId);await s.from("ra_bills").update({status:"under_checking",gross_certified_amount:(rows??[]).reduce((a,r)=>a+Number(r.certified_amount??0),0)}).eq("id",billId);revalidatePath("/projects/"+projectId+"/bills")}
async function changeBillStatus(f:FormData){"use server";const s=createClient();const projectId=tv(f,"project_id"),billId=tv(f,"ra_bill_id"),next=tv(f,"next_status");if(!projectId||!billId||!next)throw new Error("Invalid bill action.");const {data:bill}=await s.from("ra_bills").select("status,gross_certified_amount").eq("id",billId).eq("project_id",projectId).maybeSingle();if(!bill)throw new Error("Bill not found.");const allowed:Record<string,string[]>= {under_checking:["verified"],verified:["passed"]};if(!(allowed[bill.status]??[]).includes(next))throw new Error("Invalid status transition.");const patch:any={status:next};if(next==="passed"){patch.passed_amount=Number(bill.gross_certified_amount??0);patch.net_payable=Number(bill.gross_certified_amount??0)}const {error}=await s.from("ra_bills").update(patch).eq("id",billId);if(error)throw new Error(error.message);revalidatePath("/projects/"+projectId+"/bills")}

export default async function BillsPage({params}:{params:{projectId:string}}){const s=createClient();const [{data:bills},{data:measurements},{data:claimed},{data:items}]=await Promise.all([s.from("ra_bills").select("id,bill_number,period_from,period_to,status,submission_date,gross_claimed_amount,gross_certified_amount,passed_amount,net_payable,ra_bill_items(id,boq_item_id,current_claimed_quantity,previous_billed_quantity,cumulative_claimed_quantity,rate,claimed_amount,certified_quantity,certified_amount,boq_items(boq_number,description,units(code)))").eq("project_id",params.projectId).order("created_at",{ascending:false}),s.from("measurements").select("boq_item_id,measured_quantity,boq_items!inner(project_id)").eq("boq_items.project_id",params.projectId),s.from("ra_bill_items").select("boq_item_id,current_claimed_quantity,ra_bills!inner(project_id)").eq("ra_bills.project_id",params.projectId),s.from("boq_items").select("id,boq_number,description,units(code)").eq("project_id",params.projectId).order("sort_order")]);
const mm=new Map<string,number>();for(const m of measurements??[])mm.set(m.boq_item_id,(mm.get(m.boq_item_id)??0)+Number(m.measured_quantity??0));const cm=new Map<string,number>();for(const x of claimed??[])cm.set(x.boq_item_id,(cm.get(x.boq_item_id)??0)+Number(x.current_claimed_quantity??0));const available=(items??[]).map((i:any)=>({id:i.id,label:i.boq_number+" — "+i.description.slice(0,70),unit:(Array.isArray(i.units)?i.units[0]?.code:i.units?.code)??"",available:(mm.get(i.id)??0)-(cm.get(i.id)??0)})).filter(i=>i.available>0.000001);
return <div className="space-y-6"><div><h2 className="text-lg font-semibold">Running / RA Bills</h2><p className="mt-1 text-sm text-gray-500">Claim measured work only. Claimed, certified, passed and received amounts remain separate.</p></div><CreateBillForm projectId={params.projectId} action={createBill}/>
<div className="space-y-4">{(bills??[]).map((b:any)=><div key={b.id} className="rounded-xl border border-border bg-white p-4"><div className="flex items-start justify-between"><div><div className="font-semibold">RA Bill {b.bill_number}</div><div className="text-xs text-gray-500">{b.period_from} to {b.period_to}</div></div><span className="rounded-full bg-gray-100 px-2 py-1 text-xs uppercase">{b.status}</span></div><div className="mt-3 grid gap-3 md:grid-cols-4"><M l="Gross Claimed" v={pkr(Number(b.gross_claimed_amount??0))}/><M l="Certified" v={pkr(Number(b.gross_certified_amount??0))}/><M l="Passed" v={pkr(Number(b.passed_amount??0))}/><M l="Net Payable" v={pkr(Number(b.net_payable??0))}/></div>{b.status==="draft"&&available.length>0&&<BillItemForm projectId={params.projectId} billId={b.id} items={available} action={addBillItem}/>}
{b.status==="draft"&&<SubmitBill projectId={params.projectId} billId={b.id} action={submitBill}/>}
{["submitted","under_checking","verified"].includes(b.status)&&<CertificationForm projectId={params.projectId} billId={b.id} items={(b.ra_bill_items??[]).map((x:any)=>({id:x.id,label:(x.boq_items?.boq_number??"")+" — "+(x.boq_items?.description??"").slice(0,65),claimed:Number(x.current_claimed_quantity),certified:x.certified_quantity===null?null:Number(x.certified_quantity)}))} action={certifyItem}/>}
{b.status==="under_checking"&&<BillStatusAction projectId={params.projectId} billId={b.id} label="Mark checking complete / Verified" next="verified" action={changeBillStatus}/>}
{b.status==="verified"&&<BillStatusAction projectId={params.projectId} billId={b.id} label="Pass bill at certified amount" next="passed" action={changeBillStatus}/>} <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="text-xs text-gray-500"><tr><th className="py-2 text-left">BOQ</th><th className="text-left">Description</th><th className="text-right">Previous</th><th className="text-right">Current Claim</th><th className="text-right">Cumulative</th><th className="text-right">Claimed Amount</th><th className="text-right">Certified Qty</th><th className="text-right">Difference</th><th className="text-right">Certified Amount</th></tr></thead><tbody>{(b.ra_bill_items??[]).map((x:any)=>{const q=x.boq_items,u=Array.isArray(q?.units)?q.units[0]?.code:q?.units?.code;return <tr key={x.id} className="border-t border-border"><td className="py-2">{q?.boq_number}</td><td>{q?.description} <span className="text-xs text-gray-500">{u}</span></td><td className="text-right">{Number(x.previous_billed_quantity).toLocaleString()}</td><td className="text-right">{Number(x.current_claimed_quantity).toLocaleString()}</td><td className="text-right">{Number(x.cumulative_claimed_quantity).toLocaleString()}</td><td className="text-right">{pkr(Number(x.claimed_amount))}</td><td className="text-right">{x.certified_quantity===null?"—":Number(x.certified_quantity).toLocaleString()}</td><td className="text-right">{x.certified_quantity===null?"—":(Number(x.current_claimed_quantity)-Number(x.certified_quantity)).toLocaleString()}</td><td className="text-right">{x.certified_amount===null?"—":pkr(Number(x.certified_amount))}</td></tr>})}</tbody></table></div></div>)}{!(bills??[]).length&&<div className="rounded-xl border border-border bg-white px-4 py-10 text-center text-sm text-gray-500">No RA bills created yet.</div>}</div></div>}
function M({l,v}:{l:string;v:string}){return <div className="rounded-lg bg-gray-50 p-3"><div className="text-xs text-gray-500">{l}</div><div className="mt-1 font-semibold">{v}</div></div>}
